apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: dpl-multi-app
  name: dpl-multi-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dpl-multi-app
  template:
    metadata:
      labels:
        app: dpl-multi-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      - name: network-multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "10443"
